Repository Coaktion/zendesk-clients-react, pull requests merged in 2023-05, with the labels that each got.

#5 feat: Adding config for npm publish
  .github/workflows/npm-publish.yml
  .npmrc
  package-lock.json
  package.json
Labels: feature

#6 chore: changing version
  package.json
Labels: skip-changelog

#8 Release/v1.1.1
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
Labels: skip-changelog

#9 fix: ajustando instanciacao classe Zendesk
  package-lock.json
  package.json
  src/factories.tsx
  src/zendesk/tickets.ts
  src/zendesk/users.ts
  tsconfig.json
Labels: bugfix

#10 chore(release): 1.1.2
  .prettierignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog
